name: flutter_base_template
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  fade_shimmer: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^8.0.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  lottie: ^2.6.0
  package_info_plus: ^4.0.2
  page_transition: ^2.0.9
  persistent_bottom_nav_bar_v2: ^4.2.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/
